FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

# Set the working directory in the container
WORKDIR /usr/src/app

RUN apt-get update -y

# apply the relevant .env
COPY ./env-samples/.env.cuda.example ./.env

# Copy the current directory contents into the container at /usr/src/app
COPY ./LICENSE ./LICENSE
COPY ./com/ ./com/
COPY ./html ./html/
COPY ./src ./src/
COPY ./main.py ./main.py
COPY ./requirements.txt ./requirements.txt
COPY ./ui-app ./ui-app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install bitsandbytes
RUN pip install bitsandbytes

# Run main.py when the container launches
CMD ["python", "main.py", "--multiprocess"]
