FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime


# Set the working directory in the container
WORKDIR /usr/src/app

# Install build tools and compilers
# Avoid user interaction with tzdata when installing
ENV DEBIAN_FRONTEND=noninteractive

# Install build tools and compilers
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN  pip install llama-cpp-python

# Install bitsandbytes
RUN pip install bitsandbytes

# Run main.py when the container launches
CMD ["python", "main.py", "--multiprocess"]
