name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  trigger-types-build:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.TYPES_REPO_TOKEN }}

      - name: Clone, copy thrift folder, and include specific files
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          
          git clone -b dev https://github.com/alexandriaproject-io/alexandria-project-types.git
          ls
          cd alexandria-project-types
          echo $(( $(cat nonce) + 1 )) > nonce
          
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          ls

          git add .
          git commit -m "triggerd by llm-inference"
          git status
          pwd
          git remote show origin
          git push origin dev

          
          
