name: Sync thrift changes to types repository

on:
  push:
    branches:
      - github-sync-action
    paths:
      - "thrift/**"
      - "thrift_build.ps1"
      - "thrift_build.sh"
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup git config
        run: |
          git config --global user.name "LLM Inference GitHub Actions"
          git config --global user.email "llm-inference-actions@github.com"

      - name: Sync to target repository
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.TYPES_REPO_TOKEN }}
          # repository: alexandriaproject-io/alexandria-project-types
          repository: SergeSyntax/test-github-ci-cd-sync
          branch: dev
          force: true
          directory: thrift
